routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.talim');
})->name('main.page');

Route::get('main/iframe/{file}', [\App\Http\Controllers\Admin\SaytController::class, 'iframe'])->name('iframe');
Route::get('main/sayt_haqida', [\App\Http\Controllers\Admin\SaytController::class, 'sayt_haqida'])->name('sayt_haqida');
Route::get('main/muallif_haqida', [\App\Http\Controllers\Admin\SaytController::class, 'muallif_haqida'])->name('muallif_haqida');
Route::get('main/talim', [\App\Http\Controllers\Admin\SaytController::class, 'talim'])->name('talim');
Route::get('main/ilova', [\App\Http\Controllers\Admin\SaytController::class, 'ilova'])->name('ilova');
Route::get('main/form', [\App\Http\Controllers\Admin\SaytController::class, 'form'])->name('form');
Route::get('main/farmon', [\App\Http\Controllers\Admin\FarmonController::class, 'view_farmon'])->name('view.farmon');
Route::get('main/hujjat', [\App\Http\Controllers\Admin\HujjatController::class, 'view_hujjat'])->name('view.hujjat');
Route::get('main/tadqiqot', [\App\Http\Controllers\Admin\IlmiyController::class, 'view_tadqiqot'])->name('view.tadqiqot');
Route::get('main/maqola', [\App\Http\Controllers\Admin\IlmiyController::class, 'view_maqola'])->name('view.maqola');
Route::get('main/lugat', [\App\Http\Controllers\Admin\LugatController::class, 'view_lugat'])->name('view.lugat');
Route::get('main/konferensiya', [\App\Http\Controllers\Admin\KonferensiyaController::class, 'view_konferensiya'])->name('view.konferensiya');
Route::get('main/akademik', [\App\Http\Controllers\Admin\AkademikController::class, 'view_akademik'])->name('view.akademik');
Route::get('main/katalog', [\App\Http\Controllers\Admin\KatalogController::class, 'view_katalog'])->name('view.katalog');
Route::get('main/siyosat_kirish', [\App\Http\Controllers\Admin\Siyosat_kirishController::class, 'view_siyosat_kirish'])->name('view.siyosat_kirish');
Route::get('main/siyosat_metodika', [\App\Http\Controllers\Admin\Siyosat_metodikaController::class, 'view_siyosat_metodika'])->name('view.siyosat_metodika');
Route::get('main/siyosat_fanlar', [\App\Http\Controllers\Admin\Siyosat_fanlarController::class, 'view_siyosat_fanlar'])->name('view.siyosat_fanlar');
Route::get('main/savols', [\App\Http\Controllers\Admin\SavolController::class, 'view_savols'])->name('view.savols');
Route::get('main/kutubxona', [\App\Http\Controllers\Admin\KutubxonaController::class, 'view_kutubxona'])->name('view.kutubxona');
Route::get('main/havola', [\App\Http\Controllers\Admin\HavolaController::class, 'view_havola'])->name('view.havola');
Route::get('main/fotogalareya', [\App\Http\Controllers\Admin\FotogalareyaController::class, 'view_fotogalareya'])->name('view.fotogalareya');
Route::get('main/elon', [\App\Http\Controllers\Admin\ElonController::class, 'view_elon'])->name('view.elon');
Route::get('main/yangilik', [\App\Http\Controllers\Admin\YangilikController::class, 'view_yangilik'])->name('view.yangilik');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'dashboard', 'middleware'=>['auth']], function ()
{
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit'])->name('dashboard.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update'])->name('dashboard.update');
    Route::get('/sayt/create', [\App\Http\Controllers\Admin\SaytController::class, 'create_sayt'])->name('create.sayt');
    Route::post('/sayt/store', [\App\Http\Controllers\Admin\SaytController::class, 'store_sayt'])->name('store.sayt');
    Route::get('/sayt/view', [\App\Http\Controllers\Admin\SaytController::class, 'view_sayt'])->name('view.sayt');
    Route::get('/sayt/edit', [\App\Http\Controllers\Admin\SaytController::class, 'edit_sayt'])->name('edit.sayt');
    Route::post('/sayt/update', [\App\Http\Controllers\Admin\SaytController::class, 'update_sayt'])->name('update.sayt');

    Route::get('/muallif/create', [\App\Http\Controllers\Admin\SaytController::class, 'create_muallif'])->name('create.muallif');
    Route::post('/muallif/store', [\App\Http\Controllers\Admin\SaytController::class, 'store_muallif'])->name('store.muallif');
    Route::get('/muallif/view', [\App\Http\Controllers\Admin\SaytController::class, 'view_muallif'])->name('view.muallif');
    Route::get('/muallif/edit', [\App\Http\Controllers\Admin\SaytController::class, 'edit_muallif'])->name('edit.muallif');
    Route::post('/muallif/update', [\App\Http\Controllers\Admin\SaytController::class, 'update_muallif'])->name('update.muallif');

    Route::resource('/farmon', \App\Http\Controllers\Admin\FarmonController::class);
    Route::resource('/hujjat', \App\Http\Controllers\Admin\HujjatController::class);
    Route::resource('/ilmiy', \App\Http\Controllers\Admin\IlmiyController::class);
    Route::resource('/lugat', \App\Http\Controllers\Admin\LugatController::class);
    Route::resource('/konferensiya', \App\Http\Controllers\Admin\KonferensiyaController::class);
    Route::resource('/akademik', \App\Http\Controllers\Admin\AkademikController::class);
    Route::resource('/katalog', \App\Http\Controllers\Admin\KatalogController::class);
    Route::resource('/siyosat_kirish', \App\Http\Controllers\Admin\Siyosat_kirishController::class);
    Route::resource('/siyosat_metodika', \App\Http\Controllers\Admin\Siyosat_metodikaController::class);
    Route::resource('/siyosat_fanlar', \App\Http\Controllers\Admin\Siyosat_fanlarController::class);
    Route::resource('/savol-javob', \App\Http\Controllers\Admin\SavolController::class);
    Route::resource('/kutubxona', \App\Http\Controllers\Admin\KutubxonaController::class);
    Route::resource('/havola', \App\Http\Controllers\Admin\HavolaController::class);
    Route::resource('/fotogalareya', \App\Http\Controllers\Admin\FotogalareyaController::class);
    Route::resource('/elon', \App\Http\Controllers\Admin\ElonController::class);
    Route::resource('/yangilik', \App\Http\Controllers\Admin\YangilikController::class);

});

resources/views/admin/savol-javob/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Savol qo\'shish')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('savol-javob.store')}}" method="post">
                        @csrf
                        <div class="card-header">
                            <h5 class="card-title">Savol qo'shish</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Savol</div>
                                <input type="text" name="savol" class="form-control @error('savol') is-invalid @enderror">
                                @error('savol')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="mb-2">
                                <div class="col-form-label">Javob</div>
                                <input type="text" name="javob" class="form-control @error('javob') is-invalid @enderror">
                                @error('javob')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>


                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="Saqlash">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/savol-javob/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Savolni tahrirlash')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('savol-javob.update', $savols)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="card-header">
                            <h5 class="card-title">Savolni tahrirlash</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Savol</div>
                                <input value="{{$savols->savol}}" type="text" name="savol" class="form-control @error('savol') is-invalid @enderror">
                                @error('savol')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="mb-2">
                                <div class="col-form-label">Javob</div>
                                <input value="{{$savols->javob}}" type="text" name="javob" class="form-control @error('javob') is-invalid @enderror">
                                @error('javob')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>


                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="Yangilash">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/savol-javob/view.blade.php
@extends('admin.layouts.master')
@section('title', 'Barcha savollar')
@section('content')
    <br><br>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>Barcha savollar</h5>
                <a href="{{route('savol-javob.create')}}" class="btn btn-primary">Savol qo'shish</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display" id="basic-1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Savol</th>
                            <th>Javob</th>
                            <th>Qachon yaratilgan</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($savols as $key=>$savol)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$savol->savol}}</td>
                                <td>{{$savol->javob}}</td>
                                <td>{{$savol->created_at}}</td>
                                <td class="d-flex align-items-end">
                                    <a style="max-height: 40px" href="{{route('savol-javob.edit', $savol)}}" class="btn btn-success">Tahrirlash</a>
                                    <form action="{{route('savol-javob.destroy', $savol)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        &nbsp;
                                        <button type="submit" class="btn btn-danger show_confirm">O'chirish</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script type="text/javascript">
        $('.show_confirm').click(function (event){
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Do you want delete savol?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush