routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.talim');
})->name('main.page');

Route::get('main/iframe/{file}', [\App\Http\Controllers\Admin\SaytController::class, 'iframe'])->name('iframe');
Route::get('main/sayt_haqida', [\App\Http\Controllers\Admin\SaytController::class, 'sayt_haqida'])->name('sayt_haqida');
Route::get('main/muallif_haqida', [\App\Http\Controllers\Admin\SaytController::class, 'muallif_haqida'])->name('muallif_haqida');
Route::get('main/talim', [\App\Http\Controllers\Admin\SaytController::class, 'talim'])->name('talim');
Route::get('main/ilova', [\App\Http\Controllers\Admin\SaytController::class, 'ilova'])->name('ilova');
Route::get('main/form', [\App\Http\Controllers\Admin\SaytController::class, 'form'])->name('form');
Route::get('main/farmon', [\App\Http\Controllers\Admin\FarmonController::class, 'view_farmon'])->name('view.farmon');
Route::get('main/hujjat', [\App\Http\Controllers\Admin\HujjatController::class, 'view_hujjat'])->name('view.hujjat');
Route::get('main/tadqiqot', [\App\Http\Controllers\Admin\IlmiyController::class, 'view_tadqiqot'])->name('view.tadqiqot');
Route::get('main/maqola', [\App\Http\Controllers\Admin\IlmiyController::class, 'view_maqola'])->name('view.maqola');
Route::get('main/lugat', [\App\Http\Controllers\Admin\LugatController::class, 'view_lugat'])->name('view.lugat');
Route::get('main/konferensiya', [\App\Http\Controllers\Admin\KonferensiyaController::class, 'view_konferensiya'])->name('view.konferensiya');
Route::get('main/akademik', [\App\Http\Controllers\Admin\AkademikController::class, 'view_akademik'])->name('view.akademik');
Route::get('main/katalog', [\App\Http\Controllers\Admin\KatalogController::class, 'view_katalog'])->name('view.katalog');
Route::get('main/siyosat_kirish', [\App\Http\Controllers\Admin\Siyosat_kirishController::class, 'view_siyosat_kirish'])->name('view.siyosat_kirish');
Route::get('main/siyosat_metodika', [\App\Http\Controllers\Admin\Siyosat_metodikaController::class, 'view_siyosat_metodika'])->name('view.siyosat_metodika');
Route::get('main/siyosat_fanlar', [\App\Http\Controllers\Admin\Siyosat_fanlarController::class, 'view_siyosat_fanlar'])->name('view.siyosat_fanlar');
Route::get('main/savols', [\App\Http\Controllers\Admin\SavolController::class, 'view_savols'])->name('view.savols');
Route::get('main/kutubxona', [\App\Http\Controllers\Admin\KutubxonaController::class, 'view_kutubxona'])->name('view.kutubxona');
Route::get('main/havola', [\App\Http\Controllers\Admin\HavolaController::class, 'view_havola'])->name('view.havola');
Route::get('main/fotogalareya', [\App\Http\Controllers\Admin\FotogalareyaController::class, 'view_fotogalareya'])->name('view.fotogalareya');
Route::get('main/elon', [\App\Http\Controllers\Admin\ElonController::class, 'view_elon'])->name('view.elon');
Route::get('main/yangilik', [\App\Http\Controllers\Admin\YangilikController::class, 'view_yangilik'])->name('view.yangilik');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['prefix'=>'dashboard', 'middleware'=>['auth']], function ()
{
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::get('/setting', [\App\Http\Controllers\HomeController::class, 'edit'])->name('dashboard.setting');
    Route::put('/update/{user}', [\App\Http\Controllers\HomeController::class, 'update'])->name('dashboard.update');
    Route::get('/sayt/create', [\App\Http\Controllers\Admin\SaytController::class, 'create_sayt'])->name('create.sayt');
    Route::post('/sayt/store', [\App\Http\Controllers\Admin\SaytController::class, 'store_sayt'])->name('store.sayt');
    Route::get('/sayt/view', [\App\Http\Controllers\Admin\SaytController::class, 'view_sayt'])->name('view.sayt');
    Route::get('/sayt/edit', [\App\Http\Controllers\Admin\SaytController::class, 'edit_sayt'])->name('edit.sayt');
    Route::post('/sayt/update', [\App\Http\Controllers\Admin\SaytController::class, 'update_sayt'])->name('update.sayt');

    Route::get('/muallif/create', [\App\Http\Controllers\Admin\SaytController::class, 'create_muallif'])->name('create.muallif');
    Route::post('/muallif/store', [\App\Http\Controllers\Admin\SaytController::class, 'store_muallif'])->name('store.muallif');
    Route::get('/muallif/view', [\App\Http\Controllers\Admin\SaytController::class, 'view_muallif'])->name('view.muallif');
    Route::get('/muallif/edit', [\App\Http\Controllers\Admin\SaytController::class, 'edit_muallif'])->name('edit.muallif');
    Route::post('/muallif/update', [\App\Http\Controllers\Admin\SaytController::class, 'update_muallif'])->name('update.muallif');

    Route::resource('/farmon', \App\Http\Controllers\Admin\FarmonController::class);
    Route::resource('/hujjat', \App\Http\Controllers\Admin\HujjatController::class);
    Route::resource('/ilmiy', \App\Http\Controllers\Admin\IlmiyController::class);
    Route::resource('/lugat', \App\Http\Controllers\Admin\LugatController::class);
    Route::resource('/konferensiya', \App\Http\Controllers\Admin\KonferensiyaController::class);
    Route::resource('/akademik', \App\Http\Controllers\Admin\AkademikController::class);
    Route::resource('/katalog', \App\Http\Controllers\Admin\KatalogController::class);
    Route::resource('/siyosat_kirish', \App\Http\Controllers\Admin\Siyosat_kirishController::class);
    Route::resource('/siyosat_metodika', \App\Http\Controllers\Admin\Siyosat_metodikaController::class);
    Route::resource('/siyosat_fanlar', \App\Http\Controllers\Admin\Siyosat_fanlarController::class);
    Route::resource('/savol-javob', \App\Http\Controllers\Admin\SavolController::class);
    Route::resource('/kutubxona', \App\Http\Controllers\Admin\KutubxonaController::class);
    Route::resource('/havola', \App\Http\Controllers\Admin\HavolaController::class);
    Route::resource('/fotogalareya', \App\Http\Controllers\Admin\FotogalareyaController::class);
    Route::resource('/elon', \App\Http\Controllers\Admin\ElonController::class);
    Route::resource('/yangilik', \App\Http\Controllers\Admin\YangilikController::class);

});

app/Models/yangilik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class yangilik extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/YangilikController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\yangilik;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class YangilikController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $fotos = yangilik::orderBy('id', 'desc')->get();
        return view('admin.yangilik.view', compact('fotos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.yangilik.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'desc'=>'required',
            'file'=>'required|array',
            'file.*'=>'mimes:jpeg,png,jpg,svg'
        ]);
        $org_images = "";
        for ($i=0; $i<count($request->file('file')); $i++)
        {
            $all_img = $request->file('file')[$i];
            $extension = $all_img->getClientOriginalExtension();
            $fileNameToStore = time();
            $org_images .= $fileNameToStore.$i.'.'.$extension.',';
            $all_img->move(public_path('admin/yangilik'), $fileNameToStore.$i.'.'.$extension);
        }

        $foto = new yangilik();
        $foto->name = $request->input('name');
        $foto->matn = $request->input('desc');
        $foto->rasm = $org_images;
        $foto->save();

        return redirect()->route('yangilik.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($foto)
    {
        $fotos = yangilik::where('id', '=', $foto)->first();
        $images = explode(',', $fotos->rasm);
        return view('admin.yangilik.show', compact('fotos', 'images'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($foto)
    {
        $fotos = yangilik::where('id', '=', $foto)->first();
        return view('admin.yangilik.edit', compact('fotos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $foto)
    {
        $request->validate([
            'name'=>'required',
            'desc'=>'required',
            'file.*'=>'mimes:jpeg,png,jpg,svg'
        ]);
        $fotos = yangilik::where('id', '=', $foto)->first();
        if($request->hasFile('file'))
        {
            $old_images_org = explode(',', $fotos->image);
            for ($i=0; $i<count($old_images_org)-1; $i++)
            {
                File::delete(public_path('admin/yangilik/'.$old_images_org[$i]));
            }

            $org_images = '';
            for ($i=0; $i<count($request->file('file')); $i++)
            {
                $all_img = $request->file('file')[$i];
                $extension = $all_img->getClientOriginalExtension();
                $fileNameToStore = time();
                $org_images .= $fileNameToStore.$i.'.'.$extension.',';
                $all_img->move(public_path('admin/yangilik'), $fileNameToStore.$i.'.'.$extension);
            }
        }else{
            $org_images = $fotos->rasm;
        }

        $fotos->name = $request->input('name');
        $fotos->matn = $request->input('desc');
        $fotos->rasm = $org_images;
        $fotos->update();

        return redirect()->route('yangilik.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($foto)
    {
        $data = yangilik::where('id', '=', $foto)->first();
        $images = explode(",", $data->rasm);
        for($i=0; $i<count($images)-1; $i++){
            File::delete(public_path('admin/yangilik/'.$images[$i]));
        }
        yangilik::where('id', '=', $foto)->delete();
        return redirect()->route('yangilik.index');
    }

    public function view_yangilik()
    {
        $fotos = yangilik::all();
        $all_image = [];
        for ($i=0; $i<count($fotos); $i++){
            $images = explode(',', $fotos[$i]->rasm);
            $all_image[$i] = $images;
        }

        return view('main.yangiliklar.yangilik', compact('fotos', 'all_image'));
    }

    public function view_yangilik1()
    {
        $fotos = yangilik::all();
        $all_image = [];
        for ($i=0; $i<count($fotos); $i++){
            $images = explode(',', $fotos[$i]->rasm);
            $all_image[$i] = $images;
        }
        return response()->json(['success'=>true, 'data'=>$fotos, 'data1' => $all_image]);
    }
}

resources/views/admin/yangilik/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Yangilik qo\'shish')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('yangilik.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card-header">
                            <h5 class="card-title">Yangilik qo'shish</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Mavzu</div>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror">
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="mb-2">
                                <div class="col-form-label">Rasmlar</div>
                                <input multiple type="file" name="file[]" class="form-control @error('file') is-invalid @enderror" id="defaultFormControlInput" aria-describedby="defaultFormControlHelp">
                                @error('file')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }} </strong>
                                    </span>
                                @enderror
                                @foreach ($errors->get('file.*') as $error)
                                    <div class="alert alert-danger">{{ $error[0] }}</div>
                                @endforeach
                            </div>


                            <div>
                                <label for="exampleFormControlTextarea1" class="form-label">Izoh</label>
                                <textarea class="form-control @error('desc') is-invalid @enderror" name="desc" id="exampleFormControlTextarea1" rows="3"></textarea>
                                @error('desc')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>

                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="Saqlash">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/yangilik/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Yangilikni tahrirlash')
@section('content')
    <div class="select2-drpdwn">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <form action="{{route('yangilik.update', $fotos)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-header">
                            <h5 class="card-title">Yangilikni tahrirlash</h5>
                        </div>
                        <div class="card-body o-hidden">
                            <div class="mb-2">
                                <div class="col-form-label">Mavzu</div>
                                <input value="{{$fotos->name}}" type="text" name="name" class="form-control @error('name') is-invalid @enderror">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="mb-2">
                                <div class="col-form-label">Rasmlar</div>
                                <input multiple type="file" name="file[]" class="form-control @error('file') is-invalid @enderror" id="defaultFormControlInput" aria-describedby="defaultFormControlHelp">
                                @error('file')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }} </strong>
                                    </span>
                                @enderror
                                @foreach ($errors->get('file.*') as $error)
                                    <div class="alert alert-danger">{{ $error[0] }}</div>
                                @endforeach
                            </div>


                            <div>
                                <label for="exampleFormControlTextarea1" class="form-label">Izoh</label>
                                <textarea class="form-control @error('desc') is-invalid @enderror" name="desc" id="exampleFormControlTextarea1" rows="3">{{$fotos->matn}}</textarea>
                                @error('desc')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>

                            <br>
                            <div class="mb-2">
                                <input type="submit" class="btn btn-primary" value="Yangilash">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/yangilik/show.blade.php
@extends('admin.layouts.master')
@section('title', 'Yangilikni ko\'rish')
@section('content')
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>{{$fotos->name}}</h5>
                    </div>
                    <div class="card-body">
                        <p>{{$fotos->matn}}</p>
                    </div>
                    <div class="card-body">
                        <div class="row my-gallery gallery" id="aniimated-thumbnials" itemscope="" data-pswp-uid="1">
                            @for($i=0; $i<count($images)-1; $i++)
                            <figure class="col-md-3 col-6 img-hover hover-1" itemprop="associatedMedia" itemscope="">
                                <a href="{{asset('admin/yangilik/'.$images[$i])}}" itemprop="contentUrl" data-size="1600x950" data-bs-original-title="" title="">
                                    <div><img src="{{asset('admin/yangilik/'.$images[$i])}}" itemprop="thumbnail" alt="Image description"></div>
                                </a>
                                <figcaption itemprop="caption description"></figcaption>
                            </figure>
                            @endfor
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/yangilik/view.blade.php
@extends('admin.layouts.master')
@section('title', 'Barcha yangiliklarlar')
@section('content')

    <br><br>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>Barcha yangiliklar</h5>
                <a href="{{route('yangilik.create')}}" class="btn btn-primary">Yangilik qo'shish</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display" id="basic-1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Mavzu</th>
                            <th>Yangilik izohi</th>
                            <th>Qachon qo'shilgan</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($fotos as $key=>$foto)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$foto->name}}</td>
                                <td>{{$foto->matn}}</td>
                                <td>{{$foto->created_at}}</td>
                                <td class="d-flex" >
                                    <a  href="{{route('yangilik.edit', $foto)}}" class="btn btn-success">Tahrirlash</a>&nbsp;&nbsp;
                                    <a  href="{{route('yangilik.show', $foto)}}" class="btn btn-success">Ko'rish</a>
                                    <form action="{{route('yangilik.destroy', $foto)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        &nbsp;&nbsp;
                                        <button type="submit" class="btn btn-danger show_confirm">O'chirish</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script type="text/javascript">
        $('.show_confirm').click(function (event){
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Do you want delete yangilik?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush